apiVersion: v1
kind: Service
metadata:
  name: devops
  labels:
    app: devops
spec:
  type: LoadBalancer
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 31200
